
2017-12-07 12:17:58,076 p=43182 u=root |  ERROR! the playbook: aws_prepare.yml could not be found
2017-12-07 12:18:17,685 p=43203 u=root |  ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 14, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - cidr: "{{vpc_octect}}.1.0/{{vpn_prefix - 1 }}"
        az: {{ aws_region }}a
                            ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a block mapping
  in "<unicode string>", line 13, column 9
did not find expected key
  in "<unicode string>", line 14, column 29
2017-12-07 12:18:23,193 p=43211 u=root |  ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 14, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - cidr: "{{vpc_octect}}.1.0/{{vpn_prefix - 1 }}"
        az: {{ aws_region }}a
                            ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.parser.ParserError'>
exception: while parsing a block mapping
  in "<unicode string>", line 13, column 9
did not find expected key
  in "<unicode string>", line 14, column 29
2017-12-07 12:20:08,776 p=43259 u=root |  ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 7, column 18, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    state: present
    cidr_block: {{ vpc_cidr_block }}
                 ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.constructor.ConstructorError'>
exception: while constructing a mapping
  in "<unicode string>", line 7, column 17
found unacceptable key (unhashable type: 'AnsibleMapping')
  in "<unicode string>", line 7, column 18
2017-12-07 12:22:14,841 p=43304 u=root |  ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 37, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

            gw: igw
    region: {{ aws_region }}
             ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.constructor.ConstructorError'>
exception: while constructing a mapping
  in "<unicode string>", line 37, column 13
found unacceptable key (unhashable type: 'AnsibleMapping')
  in "<unicode string>", line 37, column 14
2017-12-07 12:23:14,163 p=43346 u=root |  ERROR! Syntax Error while loading YAML.


The error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 126, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#        delete_on_termination: true
    count: {{tikv_count}}
            ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.constructor.ConstructorError'>
exception: while constructing a mapping
  in "<unicode string>", line 126, column 12
found unacceptable key (unhashable type: 'AnsibleMapping')
  in "<unicode string>", line 126, column 13
2017-12-07 13:18:13,565 p=43513 u=root |  playbook: cloud/aws-ansible/aws_prepare.yml
2017-12-07 13:18:13,566 p=43513 u=root |    play #1 (localhost): do AWS preparation	TAGS: []
    pattern: [u'localhost']
    hosts (1):
      localhost
2017-12-07 13:34:51,982 p=43550 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:34:52,000 p=43550 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:34:52,033 p=43550 u=root |  fatal: [localhost]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "failed": true, "message": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in 'True': line 40, column 55, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\n(could not open file to display line)\nexception type: <class 'yaml.parser.ParserError'>\nexception: while parsing a flow mapping\n  in \"<unicode string>\", line 40, column 21\ndid not find expected ',' or '}'\n  in \"<unicode string>\", line 40, column 55"}
2017-12-07 13:34:52,035 p=43550 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:34:52,036 p=43550 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:34:52,036 p=43550 u=root |  localhost                  : ok=0    changed=0    unreachable=0    failed=1   
2017-12-07 13:40:03,482 p=43658 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:40:03,495 p=43658 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:40:03,527 p=43658 u=root |  ok: [localhost]
2017-12-07 13:40:03,533 p=43658 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:40:03,558 p=43658 u=root |  fatal: [localhost]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'vpn_prefix' is undefined\n\nThe error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# all cluster use a single vpc\n- name: vpc setup\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'vpn_prefix' is undefined"}
2017-12-07 13:40:03,561 p=43658 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:40:03,561 p=43658 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:40:03,561 p=43658 u=root |  localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2017-12-07 13:40:58,977 p=43738 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:40:58,991 p=43738 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:40:59,027 p=43738 u=root |  ok: [localhost]
2017-12-07 13:40:59,033 p=43738 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:40:59,056 p=43738 u=root |  fatal: [localhost]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'vpc_prefix' is undefined\n\nThe error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# all cluster use a single vpc\n- name: vpc setup\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'vpc_prefix' is undefined"}
2017-12-07 13:40:59,058 p=43738 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:40:59,058 p=43738 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:40:59,059 p=43738 u=root |  localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2017-12-07 13:43:14,867 p=43781 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:43:14,879 p=43781 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:43:14,910 p=43781 u=root |  ok: [localhost]
2017-12-07 13:43:14,915 p=43781 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:43:14,940 p=43781 u=root |  fatal: [localhost]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'vpc_prefix' is undefined\n\nThe error appears to have been in '/root/wyatt88/tidb-ansible/cloud/aws-ansible/roles/aws/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# all cluster use a single vpc\n- name: vpc setup\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'vpc_prefix' is undefined"}
2017-12-07 13:43:14,942 p=43781 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:43:14,943 p=43781 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:43:14,943 p=43781 u=root |  localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2017-12-07 13:44:05,639 p=43846 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:44:05,653 p=43846 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:44:05,683 p=43846 u=root |  ok: [localhost]
2017-12-07 13:44:05,689 p=43846 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:44:11,395 p=43846 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to create subnet 10.233.1.0/15, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidSubnet.Range</Code><Message>The CIDR '10.233.1.0/15' is invalid.</Message></Error></Errors><RequestID>2e14e29c-ab58-44d7-b09c-794f7d53abe4</RequestID></Response>"}
2017-12-07 13:44:11,397 p=43846 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:44:11,397 p=43846 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:44:11,397 p=43846 u=root |  localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2017-12-07 13:45:07,256 p=43884 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:45:07,269 p=43884 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:45:07,304 p=43884 u=root |  ok: [localhost]
2017-12-07 13:45:07,311 p=43884 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:45:13,236 p=43884 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to create subnet 10.233.2.0/17, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidSubnet.Conflict</Code><Message>The CIDR '10.233.2.0/17' conflicts with another subnet</Message></Error></Errors><RequestID>cc340010-e1cd-4024-8b41-f9e3299b84a0</RequestID></Response>"}
2017-12-07 13:45:13,237 p=43884 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:45:13,238 p=43884 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:45:13,238 p=43884 u=root |  localhost                  : ok=1    changed=0    unreachable=0    failed=1   
2017-12-07 13:48:56,409 p=43927 u=root |  PLAY [do AWS preparation] *****************************************************************************************************************
2017-12-07 13:48:56,421 p=43927 u=root |  TASK [include_vars] ***********************************************************************************************************************
2017-12-07 13:48:56,451 p=43927 u=root |  ok: [localhost]
2017-12-07 13:48:56,456 p=43927 u=root |  TASK [aws : vpc setup] ********************************************************************************************************************
2017-12-07 13:49:10,466 p=43927 u=root |  changed: [localhost]
2017-12-07 13:49:10,471 p=43927 u=root |  TASK [aws : tidb cluster group] ***********************************************************************************************************
2017-12-07 13:49:10,965 p=43927 u=root |  fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 required for this module"}
2017-12-07 13:49:10,966 p=43927 u=root |  	to retry, use: --limit @/root/wyatt88/tidb-ansible/retry_files/aws_prepare.retry

2017-12-07 13:49:10,967 p=43927 u=root |  PLAY RECAP ********************************************************************************************************************************
2017-12-07 13:49:10,967 p=43927 u=root |  localhost                  : ok=2    changed=1    unreachable=0    failed=1   
